### ISSUE TITLE
Set the archive bit for split XCI dumps

### ISSUE THREAD

**Issue by friedkeenan** [DarkMatterCore/gcdumptool#18]
Instead of dumping to `name.xc0`, `name.xc1`, etc., it could be dumped to `name.xci/00`, `name.xci/01` etc, where `name.xci` is a folder. You could then set the archive bit on `name.xci` using `Result fsdevSetArchiveBit(const char *path)`, which would make HOS treat `name.xci` as a file and not as a folder. This could be done for dumping NSPs as well

**Comment by DarkMatterCore** [comment]
This is already performed on NSP dumps - I use FAT32, so that's how I actually tested the produced dumps without going back to my PC.

Split XCIs + archive bit could probable be turned into an option. A lot of tools already support the `*.xc[number]` format, and SX OS uses it without having to set the archive bit at all.

**Comment by DarkMatterCore** [comment]
Fixed in aab7e24778264c46e5ffcb0c9a5deca275f28251.
