### ISSUE TITLE
Please wait... stuck!

### ISSUE THREAD

**Issue by x7l7j8cc** [DarkMatterCore/gcdumptool#6]
When i launch the app to dump a game, i insert a game (like always), but the "Please wait..." message lasts forever. i have to push the HOME button to exit.

**Comment by DarkMatterCore** [comment]
Please state your Switch's FW version, the method used to launch the application, the version of gcdumptool you are using, and the game card title name.

**Comment by DarkMatterCore** [comment]
Same setup as me, basically (5.1.0 + Hekate + Super Mario Odyssey). Can't test with SX OS or any other cartridges, though.

Using Hekate, if a crash occurs at that point, it can only mean that one of these possibilities is taking place:

* The application fails to get the update partition info (and crashes for some reason).
* The application fails to read the root HFS0 header from the game card (and crashes for some reason).
* The application fails to get the Title ID and version from the game card using the ncm service (and crashes for some reason).
* The application fails to get the game card title name and developer using the ns service (and crashes for some reason).

This would require some debugging in your end in order to find out what's wrong and fix it (preferrably using Hekate), since I can't reproduce the bug. I'll add some more output messages and put up a quick debug build for you test.

**Comment by x7l7j8cc** [comment]
Ok, wait for the debug build... i will try this with hekate and sx os.

**Comment by DarkMatterCore** [comment]
Turns out it was some kind of problem related to the SD card that got fixed after reformatting it.

**Comment by mafischer** [comment]
I just experienced this issue.

- Atmosphere: 0.8.6 
- Switch Firmware: 7.0.1
- gcdumptool: 1.0.5
- Game Card: Super Smash Bros

**Comment by DarkMatterCore** [comment]
@mafischer Hi there. Would you please test again using the latest stable release?

If you can consistently reproduce this bug on it, feel free to open a new issue.
